nsqio/nsq

_posts/2012-12-01-nsqd.md
thanks to matt: https://groups.google.com/d/msg/nsq-users/Aj1N-_MAnng/zY9uUtLIovEJ
=> updated nsqd /ping docs

apps/nsq_stat/nsq_stat.go
=> nsq_stat: add -count flag

apps/nsq_stat/nsq_stat.go
see #524 for original discussion
=> nsq_stat: deprecate --status-every in favor of --interval

nsqadmin/http.go
another missed URL encoding...
ping #522 cc @PolyviosT
=> nsqadmin: more ephemeral topic deletion issues

apps/nsq_pubsub/nsq_pubsub.go
=> nsq_pubsub: a typo fix of fatal info

Godeps, apps/nsqd/nsqd.go, contrib/nsqd.cfg.example, nsqd/gossip.go, nsqd/gossip_test.go, nsqd/http.go, nsqd/nsqd.go, nsqd/options.go, nsqd/protocol_v2_test.go, nsqd/stats.go, nsqlookupd/client_v1.go, nsqlookupd/http.go, nsqlookupd/lookup_protocol_v1.go, nsqlookupd/nsqlookupd.go, nsqlookupd/nsqlookupd_test.go, util/registrationdb/registrationdb.go, util/registrationdb/registrationdb_test.go
#526 branched against https://github.com/bitly/nsq/tree/dev
=> nsqd: gossip

Dockerfile
nsqd uses a /data dir, so let's make that available as a volume.
=> dockerfile: create /data dir

_posts/2013-12-31-docker.md
Update the Docker docs with the directions for the new image.
=> Update Docker docs for new image.

apps/nsq_to_http/nsq_to_http.go, apps/nsq_to_nsq/nsq_to_nsq.go
go-hostpool's EpsilonGreedy chooses hosts to send to based on which host has
been most performant in the past, which is a good behavior to add.
The current hostpool option round-robins with backoff on failing hosts.
=> nsq_to_{nsq,http}: add epsilon-greedy hostpool mode

README.md
=> Add dotabuff logo (readme)

.gitignore, Makefile, apps/nsqadmin/main.go, nsqadmin/context.go, nsqadmin/graphs.go, nsqadmin/http.go, nsqadmin/logger.go, nsqadmin/notify.go, nsqadmin/nsqadmin.go, nsqadmin/options.go, nsqadmin/templates/templates.go, nsqd/lookup.go, nsqd/nsqd.go, nsqd/protocol_v2_test.go, nsqlookupd/lookup_protocol_v1.go, nsqlookupd/nsqlookupd.go, nsqlookupd/nsqlookupd_test.go
pulled out of #323
RFR @jehiah
=> nsqadmin: make importable pkg

Makefile
=> build: fix make nsqadmin

bench.sh, nsqd/options.go, nsqd/protocol_v2_test.go
Leftovers from #550 
RFR @jehiah
=> nsqd: benchmark fixes

nsqd/gossip.go, nsqd/gossip_test.go, nsqd/options.go
rebased `dev` against `master` and cleaned a few things up in the tests
RFR @jehiah
=> [dev] nsqd: improve gossip test time/robustness

nsqd/http.go
I've introduced a "topic" and "channel" parameter to optionally filter the /stats query.
=> nsqd: topic/channel filter for HTTP /stats

nsqd/http.go
=> nsqd: HTTP pprof endpoints 404

nsqd/stats.go
See https://github.com/nsqio/nsq/commit/bc0a6b91633ea4438d735f751abd044cec24fd96#commitcomment-15327758
=> nsqd: fix stats data race regression

bench/bench.py, bench/requirements.txt
just making sure this thing still works...
=> bench: minor updates

apps/nsq_to_file/nsq_to_file.go, apps/nsq_to_http/nsq_to_http.go, apps/nsq_to_nsq/nsq_to_nsq.go
=> nsq_to_*: update hasArg to use flag.Visit

dist.sh, nsqadmin/http_test.go
=> dist: add windows/fix flakey test

nsqd/message.go
this is the nsqd equivalent of a very similar change in go-nsq:
https://github.com/nsqio/go-nsq/pull/175
=> DecodeMessage: skip bytes Buffer, reducing alloc overhead

nsqd/diskqueue_test.go
Please disperse there is nothing to see here.
=> nsqd: TestDiskQueueSyncAfterRead is flakey

nsqadmin/http_test.go, nsqadmin/logger.go, nsqadmin/nsqadmin_test.go, nsqadmin/options.go
Adds test cases to improve code coverage to protect against potential
compatibility conflicts moving forward.
Existing test cases refactored to leverage common test helpers within
the internal/test package to avoid code duplication and simplify
the testing effort.
=> nsqadmin: improve test coverage

nsqd/channel_test.go, nsqd/diskqueue.go, nsqd/diskqueue_test.go, nsqd/http_test.go, nsqd/in_flight_pqueue_test.go, nsqd/logger.go, nsqd/lookup_peer.go, nsqd/nsqd.go, nsqd/nsqd_test.go, nsqd/options.go, nsqd/protocol_v2_test.go, nsqd/stats_test.go, nsqd/topic_test.go
Adds test cases to improve code coverage to protect against potential
compatibility conflicts moving forward.
Existing test cases refactored to leverage common test helpers within
the internal/test package to avoid code duplication and simplify
the testing effort.
=> nsqd: improve test coverage

internal/clusterinfo/producer_test.go, internal/clusterinfo/types.go
=> nsqadmin: Fix handling of IPv6 broadcast addresses

nsqd/nsqd_test.go
=> nsqd: deflake TestReconfigure

Godeps, nsqd/client_v2.go, nsqd/protocol_v2_test.go, nsqd/stats_test.go
=> nsqd: switch to golang/snappy

nsqd/diskqueue_test.go
=> nsqd: deflake TestDiskQueueSyncAfterRead

dist.sh
=> dist: scrub file ownership for tarball

coverage.sh
avoid coveralls service failure making travis tests fail
cc @mreiferson
=> test: ignore failure to push to coveralls

internal/clusterinfo/data.go
fix [#906](https://github.com/nsqio/nsq/issues/906)
=> fix vet error in clusterinfo/data.go

nsqd/http.go
very minor, no functional change
follow-up to #921
=> nsqd: cleanup /mpub binary param check

apps/nsq_to_file/consumer_file_logger.go, apps/nsq_to_file/file_logger.go, apps/nsq_to_file/nsq_to_file.go, apps/nsq_to_file/topic_discoverer.go
A bunch of `nsq_to_file` code cleanup. I should have done a better job separating commits, shrug.
=> nsq_to_file: cleanup

apps/nsq_to_http/http.go, apps/nsq_to_http/nsq_to_http.go, nsqadmin/bindata.go
Original issue: https://github.com/nsqio/nsq/issues/998
=> nsq_to_http: use http client connect timeout

README.md
Fandom proudly used NSQ in production services.
(connected with https://github.com/nsqio/nsqio.github.io/pull/37).
=> Add Fandom logo

.travis.yml, Dockerfile
update to stable dep version https://golang.github.io/dep/
=> Update Dep to 0.4.1

ChangeLog.md, internal/version/binary.go
The Changelog is a bit of work so I figured I'd get started on it. I'm about half through it (the older half).
please take a look and feel free to suggest wording changes @jehiah @mreiferson
side note: when might we remove the deprecated `--verbose` flag? a couple releases hence I suppose?
=> release prep

README.md
This PR adds [Bytedance](https://bytedance.com/) to the `In Production` section.
We largely use NSQ in our production environment to support more and more important services. The QPS from one of our largest clusters is about 300 million at the peak time. :)
=> add Bytedance

nsqlookupd/lookup_protocol_v1.go
Turns out we just weren't cleaning things up properly in `nsqlookupd`.
Fixes #1101.
=> nsqlookupd: fix orphaned ephemeral topics in registration DB

apps/nsq_stat/nsq_stat.go, internal/clusterinfo/data.go, internal/clusterinfo/types.go, nsqadmin/http.go, nsqd/http.go, nsqd/http_test.go, nsqd/stats.go, nsqd/stats_test.go, nsqd/statsd.go
This completes the work discussed in #920 and #925 that was not included in #929.
=> nsqd/nsqadmin: optimize retrieval of client stats

contrib/nsq.spec, internal/version/binary.go
so master-branch builds don't think they are v1.1.0 release
cc @mreiferson
=> bump v1.1.1-alpha

README.md
As an important part of our Ad serving and real-time bidding system, we (SmartServing powered by n1q.com) are now using NSQ heavily in our production environment since 2017 .   
More than 1B messages get  processed by this awesome MQ at one day (may be 2B at peak time)
Thanks guys. :heart:
=> readme: add SmartServing logo  

internal/dirlock/dirlock.go, internal/dirlock/dirlock_illumos.go
=> dirlock: fix compilation on illumos.

nsqd/http.go, nsqd/http_test.go
=> nsqd: ability to request stats without mem stats

.gitignore
Signed-off-by: yapo.yang <yang_yapo@126.com>
=> ignore build folder

README.md
Oh hi, remember me?
I'm baaaaaaaaaaaaaaaaaaaack
=> is this thing on?

README.md
https://github.com/nsqio/nsqio.github.io/pull/62
=> readme: fix bytedance image ref

AUTHORS, README.md
As per https://github.com/nsqio/go-nsq/pull/297
=> *: add AUTHORS

nsqadmin/README.md
Noticed this: https://blog.sonatype.com/hijacking-of-a-known-github-id-go-bindata
=> nsqadmin: move away from go-bindata

nsqlookupd/nsqlookupd.go
fix [#1270 ](https://github.com/nsqio/nsq/issues/1270)
=> nsqlookupd: fix listen error lists incorrect address

README.md
This updates the logo list to remove some companies that appear to be no longer.
=> README: update logos list

internal/auth/authorizations.go
https://github.com/nsqio/nsq/pull/1341#issuecomment-839065228
=> look for schema separator instead of http on checking auth endpoint

.github/workflows/test.yml
=> CI: update test matrix with go-1.16

apps/nsqd/main_test.go, go.mod, go.sum
* `golang.org/x/sys` `v0.10.0`
* `github.com/BurntSushi/toml` `v1.3.2`
Resolves #1452
=> *: upgrade Go Dependencies

nsqadmin/http.go
Fixes: #1390 
https://github.com/nsqio/nsq/assets/218825/920928da-57d2-4c12-81dc-2bec85330f1f
=> nsqadmin: add admin check for topic/node thombstone endpoint

Dockerfile
=> Dockerfile: remove nsswitch.conf check

README.md
=> readme.md Add New Company 夸父炸串 In Production
