nsqio/nsq

- nsqadmin/templates/channel.html.go
- nsqadmin/templates/index.html.go
- nsqadmin/templates/lookup.html.go
- nsqadmin/templates/nodes.html.go
- nsqadmin/templates/topic.html.go
So I have created three ephemeral topics :
Then just clicked in one of them: 
Then press to delete that topic:
but surprisingly the topic is still there:
Also one more thing I saw that is even after shutdown completely all nsq services and restarting it, I could still see those three topics.
> nsqadmin: failed to delete ephemeral topic

- contrib/nsqd.cfg.example
The configuration file option for worker_id should just be id
> nsqd.cfg.example: to change the worker_id it should just be id

- nsqd/nsqd.go
If an `nsqd` cleanly exits while there are ephemeral channels with clients connected it will persist the existence of those channels to its metadata file on disk.
Upon startup, it will re-create those ephemeral channels.
If the names used for the ephemeral channels are random and not re-used upon client reconnection they are now effectively orphaned and will never be reconnected to and thus never cleaned up (something handled explicitly by disconnection of the last client).
Proposed fix is to not persist ephemeral topics and channels in the metadata file.
cc @jehiah @adamsathailo
> nsqd: orphaned ephemeral channels

- apps/nsqd/Dockerfile
- apps/nsqlookupd/Dockerfile
- nsqadmin/Dockerfile
In the pursuit of taking another swing at the NSQ Docker strategy, we're
redoing the nsqio/nsq image. Trying to keep the app builds working,
however, required us to create a deprecated_nsq_base image that they
could use as a source layer.
> Set apps to use deprecated base Docker image.

- Dockerfile
- apps/nsqd/Dockerfile
- apps/nsqd/README.md
- apps/nsqlookupd/Dockerfile
- apps/nsqlookupd/README.md
- dist.sh
- nsqadmin/Dockerfile
Now we're trying to build the smallest container possible, and only ship
one container, instead of one container per app.
The strategy is to create a `docker` target in `dist`, and add all the
binaries from the linux target to that folder. The Dockerfile is based
off of `scratch`, and adds the `docker` target in `dist` at the root of
the filesystem. Finally, we add a `ca-certificates.crt` file (pulled
from CoreOS) so that SSL will continue to work.
This gives us a Docker image with about 5MB of overhead over the
binaries, compared to our previous strategy's ~700MB. It also means that
the versions will be easier to maintain and control.
The resulting images can be used as follows:
`docker run nsqio/nsq /nsqd --version`
Where `nsqd` is the binary you want to run. Unfortunately, I believe …
> dist: single versioned Dockerfile approach

- apps/nsq_to_http/nsq_to_http.go
previously, nsq_to_http would fail on a 201, which is the response one receives when posting to elasticsearch.
> nsq_to_http: accept any 2xx response

- Dockerfile
- dist.sh
We're changing from scratch to busybox as a base image, after discussion
in #543. This gives us some free shell expansion.
I also added a step at the end of dist.sh that would take care of
tagging the image as the "latest" build, as long as there's not a hyphen
in the version number (so our "latest" build will never be an alpha or
beta, as I assume we want stability by default).
I also listed the ports used in the Dockerfile, so we can take advantage
of container linking.
> Enable shell expansion.

- nsqd/http.go
- nsqd/http_test.go
- nsqd/nsqd.go
Ready for reveiw
Adding a timestamp for start date to the json format and a readable start time and uptime to the text format for the stats endpoint
Sample text format: 
```
nsqd v0.3.3-alpha (built w/go1.4)
start_time 2015-02-21T20:25:51-08:00
uptime 1m18.478010195s
NO_TOPICS
```
Sample JSON:
```
{"status_code":200,"status_txt":"OK","data":{"version":"0.3.3-alpha","health":"OK","start_time":1424579151,"topics":[]}}
```
> Issue 533 -Adding start time to nsqd

- apps/nsq_to_http/nsq_to_http.go
Hi, we're using nsq_to_http as a source for dark traffic testing--it's great!
Would you guys be open to consuming the request body? It adds the overhead of the round trips incurred by body bytes, but otherwise causes all types of transport errors on the other side should the endpoint expect to return a body.
This doesn't change functionality at all (I think.)
> exhaust request body

- test.sh
-depth specifies depth first search for processing directories.
-maxdepth specifies how deep in directories to go.
> test.sh: fix find flag -depth to -maxdepth

- nsqd/http_test.go
- nsqd/nsqd.go
Previously, specifying -tls-client-auth-policy would set -tls-required to
TLSRequired, overriding TLSRequiredExceptHTTP if it was specified.
Now, specifying the policy only sets TLSRequired if the current option is
TLSNotRequired.
> nsqd: fix -tls-required=tcp-https with -tls-client-auth-policy

- nsqd/protocol_v2.go
When nsqd shuts down, protocol_v2 responds to CLS with CLOSE_WAIT and then the
IOLoop waits for another command with ReadSlice on the buffered client
connection. ReadSlice returns EOF because the client closes the connection;
this error is returned from IOLoop to the tcp handler and printed.
Because the presence of EOF is expected when the client is in stateClosing, the
error should be ignored.
> nsqd: do not print EOF when closing cleanly

- internal/lookupd/types.go
- internal/quantile/aggregate.go
See commit comments.  `nsqadmin` and `nsq_stat` are the only bundled
apps that end up using this code path and currently panic.
cc @cespare
RFR @jehiah
> quantile: nil deref

- Godeps
when I run go get github.com/bitly/go-nsq,it fails with the following:
package code.google.com/p/snappy-go/snappy: Get https://code.google.com/p/snappy-go/source/checkout?repo=: dial tcp 216.58.221.46:443: i/o timeout
> build: go get fails due to "snappy"

- nsqd/channel.go
- nsqd/http.go
- nsqd/nsqd.go
- nsqd/nsqd_test.go
- nsqd/topic.go
:laughing: :laughing: :laughing: 
reasons:
1. the in-memory metadata is incomplete;
2. nsqd triggers N (where N >= # of topics + channels)
times `PersistMetadata` call which is unnecessary;
3. nsqd will persist metadata after loading.
> nsqd: skip persist metadata while loading

- nsqd/nsqd_test.go
:cry: :cry: :cry: :cry: :cry: 
detail: https://travis-ci.org/bitly/nsq/jobs/60022415
seems like concurrency issue.
> nsqd: fix testcase concurrency issue in pull request #575

- nsqd/protocol_v2_test.go
In particular, `BenchmarkProtocolV2Pub32k`:
```
$ go test -bench=ProtocolV2Pub32k -run=XXX                                                                                                                                                                                      !
PASS
BenchmarkProtocolV2Pub32k       panic: write tcp 127.0.0.1:55383: connection reset by peer
goroutine 26 [running]:
github.com/bitly/nsq/nsqd.func·051()
/home/caleb/p/go/src/github.com/bitly/nsq/nsqd/protocol_v2_test.go:1427 +0x36e
created by github.com/bitly/nsq/nsqd.benchmarkProtocolV2Pub
/home/caleb/p/go/src/github.com/bitly/nsq/nsqd/protocol_v2_test.go:1443 +0x68d
goroutine 1 [chan receive]:
testing.(*B).run(0xc208070400, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/caleb/apps/go/src/testing/benchmark.go:180 +0x67 …
```
> nsqd: benchmark panics

- Godeps
- nsqd/http.go
- nsqd/http_test.go
- nsqd/message.go
- nsqd/protocol_v2.go
- nsqd/protocol_v2_test.go
- nsqd/topic.go
This came up on the mailing list: https://groups.google.com/forum/#!topic/nsq-users/HkoOMygaHK0 - just opening the issue here for others to weigh in and gauge interest.
This would allow you to `PUB` a message that goes directly to the deferred priority queue with the specified delay.
Also, It's complicated a bit by #34.
> nsqd: support deferred PUB

- internal/util/rand.go
- nsqd/channel.go
- nsqd/channel_test.go
- nsqd/nsqd.go
- nsqd/options.go
- nsqd/protocol_v2_test.go
Background: We need to dispatch user messages to a specific topic, where every consumer only subscribe the message for a fixed range of user. Since nsqd doesn't support partitions by key, we created thousands of topics/channels, i.e. user_topic_[0-999], one topic for a range of users.
Let's suppose there will be 10K topics and channels, we want to know that whether nsqd will work well or not in this situations.
1. file number limit of process. This is easy to increase it.
2. memory consumption? After some trying, seems not so much memory consumption.
3. High cpu usage even if EMPTY workload. About 40% - 60% for one nsqd process, while no producer or consumer connect to it. `strace` tells there are lots of futex syscall.
@xiaost helps to troubleshoot, it may be caused by the 100ms ticker …
> nsqd: questions for large number of topics/channels

- nsqlookupd/registration_db.go
without '*' expression of topic & channel, we can fetch results from map directly.
it is another issue we found in #577, nsqlookupd eat up my CPUs :cry:
> nsqlookupd: improved performance of registration db.

- nsqd/guid.go
- nsqd/nsqd.go
This isn't passing travis on my repo, but not sure why, it's not building at all.
> Make the GUID code a bit more robust

- nsqd/nsqd.go
- nsqd/options.go
- nsqd/protocol_v2_test.go
- nsqd/stats.go
I did the math wrong in #429, it's actually 10-bit width not 12-bit :(
RFR @jehiah
> nsqd: fix valid range for --worker-id

- nsqd/channel.go
- nsqd/diskqueue.go
- nsqd/diskqueue_test.go
- nsqd/message.go
- nsqd/topic.go
> nsqd: enforce minimum msg size when reading from the diskqueue

- internal/http_api/api_response.go
- nsqadmin/http.go
- nsqd/http.go
- nsqd/http_test.go
- nsqlookupd/http.go
This adds a log decorator as middleware for the HTTP handlers.
Notably, this does not log /pub /mpub (should it?).
This also adds 404, 405, and "panic" handlers so that those responses
are consistently formatted.
RFR @jehiah
> nsq*: log HTTP requests

- internal/http_api/api_response.go
- nsqadmin/http.go
This fixes a regresion from #610 where some responses from nsqadmin were not handled properly (notably errors and /static/... assets)
RFR @mreiferson
> nsqadmin: format responses

- nsqd/protocol_v2_test.go
in nsqd dir:
```
go test -bench=BenchmarkProtocolV2Sub256
2015/08/06 22:27:56 http: TLS handshake error from 127.0.0.1:36493: tls: client didn't provide a certificate
2015/08/06 22:27:56 LOOKUPD: querying http://127.0.0.1:56163/channels?topic=cluster_test1438892876
PASS
BenchmarkProtocolV2Sub256	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ca3d7]
goroutine 1023 [running]:
github.com/bitly/nsq/nsqd.readValidate(0x0, 0x7fe40366cc10, 0xc2080fca48, 0x7fe400000000, 0x8b6590, 0x2, 0x0, 0x0, 0x0)
/home/dieter/go/src/github.com/bitly/nsq/nsqd/protocol_v2_test.go:103 +0x517
github.com/bitly/nsq/nsqd.sub(0x0, 0x7fe403680dc8, 0xc2080fca48, 0xc2085c07c0, 0x17, 0x8bd8d0, 0x2)
/home/dieter/go/src/github.com/bitly/nsq/nsqd/protocol_v2_test.go …
```
> nsqd: bench=BenchmarkProtocolV2Sub256 panics

- nsqd/diskqueue_test.go
also, make the statement less strong. runs fine by default on my system
with SSD.
> update invocation syntax

- nsqd/diskqueue_test.go
because this has a big impact on performance
caveats:
* if /tmp runs full, you'll get unrealistically high results,
can be avoided by running with -benchtime=0.1s
* for some reason on my system QueueGet > 1024 hangs
```
on my system:
BenchmarkDiskWrite16      300000               465 ns/op          34.36 MB/s
BenchmarkDiskWrite64      300000               476 ns/op         134.30 MB/s
BenchmarkDiskWrite256     300000               521 ns/op         491.03 MB/s
BenchmarkDiskWrite1024    200000               634 ns/op        1614.39 MB/s
BenchmarkDiskWrite4096    200000              1060 ns/op        3860.56 MB/s
BenchmarkDiskWrite16384    50000              2672 ns/op        6131.59 MB/s
BenchmarkDiskWrite65536    20000             10629 ns/op        6165.22 MB/s
BenchmarkDiskWrite262144 …
```
> nsqd: benchmark various write/msg sizes

- nsqd/diskqueue_test.go
current master (fd6260466583555ba8e9a4884a7f39cabb36f893)
```
go test -bench=QueuePut
2015/08/06 22:54:51 http: TLS handshake error from 127.0.0.1:58649: tls: client didn't provide a certificate
2015/08/06 22:54:51 LOOKUPD: querying http://127.0.0.1:36858/channels?topic=cluster_test1438894491
PASS
BenchmarkDiskQueuePut	 1000000	      1890 ns/op	 541.51 MB/s
--- BENCH: BenchmarkDiskQueuePut
nsqd_test.go:57: DISKQUEUE(bench_disk_queue_put11438894496): writeOne() opened /tmp/nsq-test-1438894496364087961502926977/bench_disk_queue_put11438894496.diskqueue.000000.dat
nsqd_test.go:57: ERROR: reading from diskqueue(bench_disk_queue_put11438894496) at 0 of /tmp/nsq-test-1438894496364087961502926977/bench_disk_queue_put11438894496.diskqueue.000000.dat - open …
```
> nsqd: BenchmarkDiskQueuePut prints errors

- nsqd/protocol_v2.go
NSQd does not distinguish io.EOF.
nsq/nsqd/protocol_v2.go
```Golang
line, err = client.Reader.ReadSlice('\n')
if err != nil {
if atomic.LoadInt32(&client.State) == stateClosing {
err = nil 
} else {
err = fmt.Errorf("failed to read command - %s", err)
}   
break
}
```
> nsqd: io.EOF when client-conn is closed

- Dockerfile
- dist.sh
Is there a reason that / is set to /dist/docker/bin for the docker image?
I would like to use nsq_to_file and output messages to /dev/null to avoid the queues filling up my server disks while testing, which is not possible because of this.
> docker: root directory is /dist/docker/bin

- apps/nsqd/nsqd.go
what's the right way to specify this option?
like `-e2e-processing-latency-percentile=90,99` ? or `.90,.99` since some of the code suggests it should be a float?
> docs: --e2e-processing-latency-percentile format unclear

- apps/nsq_stat/nsq_stat.go
- apps/nsq_to_file/nsq_to_file.go
- apps/nsqadmin/main.go
- apps/nsqd/nsqd.go
- internal/auth/authorizations.go
- internal/clusterinfo/data.go
- internal/http_api/api_request.go
- internal/http_api/http_server.go
- nsqadmin/http.go
- nsqadmin/nsqadmin.go
- nsqadmin/options.go
- nsqd/http.go
- nsqd/nsqd.go
- nsqd/nsqd_test.go
- nsqlookupd/nsqlookupd_test.go
From https://groups.google.com/d/msg/nsq-users/PkkPN9z7gPc/6EgTyHmuvg0J
`nsqadmin` cannot correctly negotiate TLS when `nsqd` in the cluster are configured with `--tls-required`.
Not sure yet how to fix this, some thoughts:
1. `nsqadmin` needs to be able to specify scheme in the `--nsqd-http-address` flag
2. `nsqd` needs to propagate TLS status to `nsqlookupd`, which needs to return this in its API responses
3. `nsqadmin` will pivot on (1) and (2) to negotiate which scheme to use
Thoughts @jehiah?
> nsqadmin: doesn't handle nsqd --tls-required flag

- internal/clusterinfo/data.go
Something in the change of [`GetLookupdProducers`](https://github.com/nsqio/nsq/pull/421/files#diff-b6cc96c8e9cf50b076b921c9089d220cR179) from #421 broke the de-duping of hosts in nsqadmin when configured to query multiple nsqlookupds.
cc: @mreiferson
> nsqadmin: dedupe of producers from lookupd not working

- apps/nsqadmin/main.go
- internal/clusterinfo/data.go
This fixes the regression mentioned [here](https://github.com/nsqio/nsq/pull/642/files#r40002100)
cc: @mreiferson
> nsqadmin: fix regression when querying nsqd directly

- apps/nsq_to_http/nsq_to_http.go
- apps/nsq_to_nsq/nsq_to_nsq.go
- apps/nsqd/nsqd.go
- apps/nsqd/nsqd_test.go
- apps/nsqlookupd/nsqlookupd.go
- internal/quantile/quantile.go
- nsqadmin/notify.go
- nsqd/client_v2.go
- nsqd/http.go
- nsqd/protocol_v2_test.go
- nsqlookupd/http.go
This adds the hostname that nsqadmin is access through, and the host running nsqadmin to the context of nsqadmin notifications. This is particularly useful if you have the same topics and channels in more than one cluster (say different datacenters) and you want to be able to disambiguate between the two.
> nsqadmin: disambiguate nsqadmin notifications

- apps/nsqadmin/main.go
- nsqadmin/static/js/lib/handlebars_helpers.js
See issue https://github.com/nsqio/nsq/issues/655
> nsqadmin: Update statsd counters prefix from 'stats_counts' to 'stats.counters'

- internal/clusterinfo/data.go
This improves nsqadmin to show actual errors when unable to query all configured nsqd or nsqlookupd instances. Previously it left the specific error out which made it hard to troubleshoot. (@mreiferson if you'd prefer it only log the specific error i'm ok w/ that too)
This also updates the backwards compatability added in #652 to default hostname to the same value as BroadcastAddress.
> nsqadmin: improve error logging

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
I'd love to see a Code of Conduct instituted for NSQ. [Go is adopting one](https://groups.google.com/d/msg/golang-nuts/sy-YcVPADjg/bcO6LAr29EIJ) and we could use that. The [Geek Feminism wiki](http://geekfeminism.wikia.com/wiki/Code_of_conduct) has examples of other good Codes of Conduct.
It would be great to have the Code of Conduct added to the README and website, to govern conduct on IRC, the mailing list, and the issue tracker.
I know I only sporadically contribute to NSQ, but this would help me feel much better about my contributions and would enable future contributions, from me and others.
> docs: code of conduct

- Makefile
`EXAMPLES` var is obsolete since 6813a90665
`BINARIES` var is obsolete since 7e8119943c
The `$(abspath ...)` in the build recipe is obsolete since f648107bd1
The `install` target intended to depend upon all the stuff being built, but since the variables changed, it no longer did. With this, you can once again build and install in one go.
before:
```
$ make PREFIX=$HOME install
install -m 755 -d /Users/pierce/bin
install -m 755 build/apps/nsqlookupd /Users/pierce/bin/nsqlookupd
install: build/apps/nsqlookupd: No such file or directory
```
after:
```
$ make PREFIX=$HOME install
go build  -o build/nsqd ./apps/nsqd
go build  -o build/nsqlookupd ./apps/nsqlookupd
go build  -o build/nsqadmin ./apps/nsqadmin
go build  -o build/nsq_pubsub ./apps/nsq_pubsub
go build  -o build/nsq_to_nsq …
```
> Makefile fixes and cleanup

- dist.sh
Clean up temp install dir, plus some other subjective cleanups.
(`rm -f` does not return error if the target does not exist)
> dist.sh cleanups

- nsqd/guid.go
Humble idea inspired by #658 
Current-nanosecond-time and 64-bit division operations
appear to be slow on some ARM systems, so minimize them:
* share time.Time from each loop of idPump() with NewGUID()
* avoid adding a second to lastError on each iteration,
by making it nextErrorLog instead
* replace division by 1000000 with a bitshift
equivalent to division by 1048576
My benchmarks on darwin / x86_64 laptop (which will depend on temperature and other factors of course) show a negligible improvement, but it will be interesting to see the results for an ARM system (I have a raspberry pi I could dig out and try, maybe later).
before:
```
PUB: [bench_writer] 2015/09/29 19:52:57 duration: 10.000785444s - 42.458mb/s - 222602.516ops/s - 4.492us/op
SUB: [bench_reader] 2015/09/29 19:53:07 …
```
> nsqd: optimize guid generation

- nsqd/lookup.go
- nsqd/lookup_peer.go
Hi there,
I've been reconfiguring our deploy getting ready to launch our product and have been hitting brick wall after brick wall with an out of memory issue. At first I thought it was an issue with my VPC configuration so I created a clean instance and succeeded (with and without docker) to reproduce the issue.
It might be something Amazon has done lately with their AMI images, but everything was working fine a few weeks ago so wanted to check in and see if it's anything on your end.
1. Set up a new AWS instance (tried t2.micro and t2.small, they've had sufficient memory in the past)
1. Download and untar the binaries - `wget https://s3.amazonaws.com/bitly-downloads/nsq/nsq-0.3.5.linux-amd64.go1.4.2.tar.gz && tar zxvf nsq-0.3.5.linux-amd64.go1.4.2.tar.gz`
1. Make the binaries …
> nsqd: OOM when misconfiguring lookupd addresses

- internal/dirlock/dirlock.go
- internal/dirlock/dirlock_windows.go
- nsqd/nsqd.go
```
panic: runtime error: makeslice: len out of range
goroutine 16 [running]:
github.com/bitly/nsq/nsqd.(*diskQueue).readOne(0xc2080d4160, 0x0, 0x0, 0x0, 0x0, 0x0)
/Users/cheney/Projects/GoProject/src/github.com/bitly/nsq/nsqd/diskqueue.go:264 +0x56a
github.com/bitly/nsq/nsqd.(*diskQueue).ioLoop(0xc2080d4160)
/Users/cheney/Projects/GoProject/src/github.com/bitly/nsq/nsqd/diskqueue.go:576 +0x706
created by github.com/bitly/nsq/nsqd.newDiskQueue
/Users/cheney/Projects/GoProject/src/github.com/bitly/nsq/nsqd/diskqueue.go:92 +0x403
```
This panic above is cause by 
```{go}
readBuf := make([]byte, msgSize)
```
I assume that maybe `msgSize` is negative, and running multiple instances in the same directory is possible?
> nsqd: panic when running two instances with same -data-path

- dist.sh
Since cross-compiling is so easy with the release of Go 1.5, could you please supply FreeBSD binaries?
> FreeBSD builds

- nsqd/channel.go
- nsqd/channel_test.go
- nsqd/nsqd.go
- nsqd/nsqd_test.go
- nsqd/topic.go
- nsqd/topic_test.go
- `channel` and `topic` `put` reset `ctx.nsqd.SetHealth`
- change `NSQD` `SetHealth`/`GetError` to use `atomic.Value`; skip allocation in `SetHealth` if attempting to set an already healthy queue to healthy
- nsqd_test.go: change `exp` to `nexp` in `nequal` output
- relates to #594
---
> nsqd topic/channel: reset health on successful backend write

- nsqd/channel.go
- nsqd/channel_test.go
- nsqd/diskqueue.go
- nsqd/topic.go
- nsqd/topic_test.go
- purpose: diskqueue was enforcing a maxmsgsize of the whole message
including header, while protocol enforces maxmsgsize on the body. this
could lead to successful writes to the memory queue but failed writes
to the diskqueue, intermittently if the body size was within the
26 bytes range.
- channel / topic tests assert configuration is passed correctly to
diskqueue; it doesn't test PutMessage directly because enforcing msg
size is the responsibility of protocol.
- add maxMsgSize to diskqueue writeOne error message.
> nsqd: add msg header size to diskqueue MaxMsgSize

- internal/test/fakes.go
- nsqd/http.go
- nsqd/nsqd.go
- nsqd/protocol_v2.go
- nsqd/protocol_v2_test.go
- nsqlookupd/lookup_protocol_v1.go
- nsqlookupd/lookup_protocol_v1_test.go
- nsqlookupd/nsqlookupd_test.go
`go tool vet -shadow` reported `lookup_protocol_v1.go:40: declaration of err shadows declaration at lookup_protocol_v1.go:25:`
In the current implementation `IOLoop` returns `nil` if there is an error other than from `reader.ReadString`. I considered if this was intentional but couldn't find a reason; if there is one please let me know.
This seems to only affect logging in `tcp.go`, however it is an exported method:
```go
...
err = prot.IOLoop(clientConn)
if err != nil {
p.ctx.nsqlookupd.logf("ERROR: client(%s) - %s", clientConn.RemoteAddr(), err)
return
}
}
```
Starting at line 49 in `nsqlookupd/lookup_protocol_v1.go`, is the second `err` check necessary?
```go
_, err = protocol.SendResponse(client, []byte(err.Error()))
if err != nil {
break
}
// errors of type FatalClientErr should …
```
> nsqd/nsqlookupd: IOLoop fix err shadow

- internal/test/assertions.go
Promoting some common test functions in the project to its own internal package.
Example Usage:
```go
import (
"testing"
"github.com/nsqio/nsq/internal/test"
)
func TestAwesomesauce(t *testing.T) {
// do some awesomeness
test.Equal(t, svc.StartPending, changes[0].State)
test.Nil(t, wsf.ws.getError())
}
```
> add common test funcs to internal/test

- nsqd/stats.go
While maxing out (reading and writing) my local nsqd with many topics (9 in this case), I noticed calling the stats api causes all requests from my consumers and producers to timeout and the stats call, if completed, takes around 14 seconds.
I believe this is caused by unneeded locking in the GetStats method. Removing the deferred and moving the RUnlock fixes the issue. During high load the stats call remained under 2ms and the consumers and producers no longer timeout. Tested with the race detector and everything looks good.
> nsqd: stats call times out requests during high load

- nsqd/channel.go
- nsqd/client_v2.go
- nsqd/http_test.go
- nsqd/protocol_v2.go
- nsqd/protocol_v2_test.go
- nsqd/stats.go
While evaluating a production performance issue I uncovered some
unnecessary lock contention inside the channel and client code
paths.
The ultimate cause of the issue was that we held client-wide, 
channel-wide (and ultimately NSQ-wide, see #700) locks during network 
operations, and if those operations block it would prevent other 
simultaneous, unrelated, operations from making progress.
> nsqd: reduce client/channel lock contention

- nsqd/nsqd.go
- nsqd/topic.go
In `AggregateChannelE2eProcessingLatency` the channels should be copied out with lock and this lock should be outside the stream merge. Also the GetTopic is hot while pub message, so we should avoid write lock as more as possible.
> nsqd: optimize GetTopic / fix data race

- Godeps
- apps/nsqd/nsqd.go
- apps/nsqlookupd/nsqlookupd.go
This approach expunges the `main.go` and `main_windows.go` files, keeping only the original `nsqd.go` and `nsqlookupd.go` which can be built on all platforms.
The `// +build` responsibility is moved to the `github.com/judwhite/go-svc/svc` package. This package exposes two interfaces and a single `Run` function. Replaces #676.
> nsqd/nsqlookupd: support running as windows service

- Makefile
- dist.sh
also threw in some other subjective Makefile refactoring, but would be fine with undoing it
new dist.sh output:
```
... building v0.3.7 for freebsd/amd64
go build  -o build/nsqd ./apps/nsqd
go build  -o build/nsqlookupd ./apps/nsqlookupd
go build  -o build/nsqadmin ./apps/nsqadmin
go build  -o build/nsq_pubsub ./apps/nsq_pubsub
go build  -o build/nsq_to_nsq ./apps/nsq_to_nsq
go build  -o build/nsq_to_file ./apps/nsq_to_file
go build  -o build/nsq_to_http ./apps/nsq_to_http
go build  -o build/nsq_tail ./apps/nsq_tail
go build  -o build/nsq_stat ./apps/nsq_stat
go build  -o build/to_nsq ./apps/to_nsq
install -m 755 -d /var/folders/ny/tsl8z9qx453630cxnzw0_dj80000gn/T/nsq.l5IgN3bd/nsq-0.3.7.freebsd-amd64.go1.5.3/bin
for APP in nsqd nsqlookupd nsqadmin nsq_pubsub nsq_to_nsq nsq_to_file …
```
> make: install windows binaries with .exe extension

- nsqd/diskqueue.go
- nsqd/diskqueue_test.go
hi，
i have a question about nsqd persisted meta file update.
my nsqd version:
> nsqd v0.3.7 (built w/go1.6)
when nsqd start up, it load persisted data from disk, and then subscriber consumed the msg, but the nsqd not update the persist meta file, and then if nsqd crash when it restart, my subscriber will consume the same messages again. I know nsqd guarantees "messages are delivered at least onceAnchor link for: messages are delivered at least once"， but is this scene can improve？
> nsqd: persisted data repeatedly consumed

- dist.sh
results in 30% smaller binaries
backtraces should still be fine
inspired by / see also: https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/
> dist.sh: strip release builds of debug info

- nsqd/channel.go
- nsqd/channel_test.go
- nsqd/nsqd_test.go
- nsqd/protocol_v2.go
- nsqd/protocol_v2_test.go
(Pushing up rebased branches I've had laying around locally for ages)
This removes a goroutine per channel and simplifies exit logic.
> nsqd: remove channel messagePump

- Godeps
Fixes #756 
Relevant change: https://github.com/judwhite/go-svc/commit/be413dcfeab775d95ca5decaa588887438f197c2#diff-2ac5da282c671a5f874701b939d24f13L16
Travis: https://travis-ci.org/judwhite/go-svc/builds/127990343
/cc @mpe
> nsqd: bump go-svc to properly handle SIGTERM

- Godeps
- apps/nsqd/nsqd.go
- apps/nsqlookupd/nsqlookupd.go
Godeps will be updated once https://github.com/judwhite/go-svc/pull/1 lands
Related PR #757 
Side note: I'll look at #743 later today since you asked for an extra set of :eyes: 
/cc @mreiferson @jehiah
> nsqd/nsqlookupd: explicitly set exit signals

- Dockerfile
Adds a variant for NSQ leveraging alpine as the base image.
Alpine is equally as small as busybox (~5 MB) but has more features
including the ability to install other packages.
> docker: Adds support for alpine as base image

- nsqadmin/http.go
- nsqadmin/http_test.go
- nsqadmin/notify.go
- nsqadmin/nsqadmin.go
Provides the ability to modify the configuration nsqadmin for setting
`nsqlookupd_http_addresses` to support dynamic configuration.
Closes #769
> nsqadmin: add /config API

- apps/nsq_stat/nsq_stat.go
- apps/nsq_to_file/nsq_to_file.go
- apps/nsq_to_http/http.go
- apps/nsq_to_http/nsq_to_http.go
- apps/nsqadmin/main.go
- apps/nsqd/nsqd.go
- contrib/nsqd.cfg.example
- internal/auth/authorizations.go
- internal/http_api/api_request.go
- nsqadmin/bindata.go
- nsqadmin/http.go
- nsqadmin/nsqadmin.go
- nsqadmin/options.go
- nsqd/client_v2.go
- nsqd/nsqd.go
- nsqd/nsqd_test.go
- nsqd/options.go
- nsqlookupd/nsqlookupd_test.go
Adds configuration options HTTPClientConnectTimeout and
HTTPClientRequestTimeout to control the connection and request timeout
repectively of the HTTP client.
Also added to the following app binaries:
- nsqadmin
- nsq_stat
- nsq_to_file
- nsq_to_http
Closes #715
Closes #680
> nsqd: configurable HTTP client transport timeout

- .gitignore
- .travis.yml
- README.md
- coverage.sh
Adds script for generating code coverage statistics for Go packages.
Borrowed from https://github.com/hashicorp/vault
> coverage.sh: adds Code Coverage generation

- internal/test/assertions.go
- internal/test/logger.go
- nsqlookupd/http_test.go
- nsqlookupd/logger.go
- nsqlookupd/lookup_protocol_v1_test.go
- nsqlookupd/nsqlookupd_test.go
- nsqlookupd/options.go
- nsqlookupd/registration_db_test.go
Adds test cases to improve code coverage to protect against potential
compatibility conflicts moving forward.
Existing test cases refactored to leverage common test helpers within
the internal/test package to avoid code duplication and simplify
the testing effort.
> nsqlookupd: improve test coverage

- nsqd/diskqueue_test.go
Adds a delay retry when attempting to opening metadata file as part
of TestDiskQueueSyncAfterRead to handle timing issue between the
ioloop and possible disk IO delays.
> nsqd: adds delayed retry to TestDiskQueueSyncAfterRead

- nsqlookupd/lookup_protocol_v1.go
As #786 , I remove conn.Close() in nsqlookupd tcp IOLoop like nsqd.
> nsqlookupd: Add conn.Close() in Tcp IOLoop

- apps/to_nsq/README.md
- apps/to_nsq/to_nsq.go
This adds a `--rate=int` option to `to_nsq` which will throttle the message creation to that rate per second:
```
-rate int
Throttle messages to n/second. 0 to disable
```
This is helpful when you want to load a large dataset into a message driven pipeline w/o causing a backlog of messages to process on the NSQ side.
> apps/to_nsq: add --rate to throttle message creation

- apps/nsq_to_file/nsq_to_file.go
fixes #789 
Notes:
- It's a little odd you can specify `--topic-pattern` without `--topic` only when using `--lookupd-http-address`; seems like this should work for `--nsqd-tcp-address` too.
- While testing I accidentally ran `nsq_to_file --topic [topic1] [topic2] ...`, which didn't produce an error, but I wondered why `topic2` wasn't getting picked up.
- Thought (too much) about the `if pattern == ""` in `allowTopicName`. I think the alternative is to set it to `.*` if it's empty once we've determined `len(topics) > 0` in `main()`. I don't have a strong opinion so leaving it to review.
Release notes should indicate people previously using default settings to archive all topics will need to change their command line args.
RFR /cc @mreiferson @jehiah @elubow
> nsq_to_file: require --topic or --topic-pattern

- nsqd/diskqueue_test.go
`BenchmarkDiskQueueGet4096` will put invalid messages if maxMsgSize is `1<<10`.
> nsqd: fix diskqueue benchmark test, maxMsgSize too small

- nsqd/channel.go
- nsqd/protocol_v2_test.go
- nsqd/topic.go
> nsqd: more intuitive channel message accounting

- Godeps
- nsqd/nsqd.go
Addresses proposal (1) and (2) of #826
> nsqd: bump go-options / log when we can't get channels for pre-creation

- nsqd/http.go
- nsqd/protocol_v2.go
> nsqd: bound MPUB messages to derived limit

- nsqd/lookup.go
- nsqd/nsqd.go
another piece to fix #826 
When using nsqlookupd with no explicit broadcast address, and without the fix in #837, it looks like this:
```
[nsqlookupd] 2016/12/29 13:01:26.395092 CLIENT(127.0.0.1:53473): IDENTIFY Address:plo-pro.local TCP:4150 HTTP:4151 Version:0.3.8
[nsqlookupd] 2016/12/29 13:01:26.395115 DB: client(127.0.0.1:53473) REGISTER category:client key: subkey:
[nsqd] 2016/12/29 13:01:26.395325 LOOKUPD(127.0.0.1:4160): peer info {TCPPort:4160 HTTPPort:4161 Version:0.3.8 BroadcastAddress:}
[nsqd] 2016/12/29 13:01:26.395337 LOOKUPD(127.0.0.1:4160): ERROR - no broadcast address
...
[nsqd] 2016/12/29 13:01:27.468701 TOPIC(t1): created
[nsqd] 2016/12/29 13:01:27.468721 ERROR: no available nsqlookupd to query for channels to pre-create for topic t1
```
I think the `ErrList` used in …
> nsqd: log errors if no nsqlookupd broadcast address

- apps/nsqlookupd/nsqlookupd.go
This updates `nsqlookupd` so that default values from the options struct
are passed into flag defaults since all flag values implement `flag.Getter`
and the recent change to `go-options` (mreiferson/go-options#15) was insufficient.
RFR @jehiah
cc @ploxiln
Fixes #826
> nsqlookupd: pass defaults from opts into flags

- internal/version/binary.go
This bumps the version to 1.0.0-alpha after #837 
RFR @mreiferson
> 1.0.0-alpha version bump

- nsqd/channel.go
Fixes #760
RFR @jehiah
cc @judwhite
> nsqd: replace missing requeue exit check; cleanup doRequeue

- nsqd/channel_test.go
- nsqd/guid.go
- nsqd/guid_test.go
- nsqd/http.go
- nsqd/nsqd.go
- nsqd/nsqd_test.go
- nsqd/protocol_v2.go
- nsqd/protocol_v2_test.go
- nsqd/stats_test.go
- nsqd/topic.go
- nsqd/topic_test.go
(Pushing up rebased branches I've had laying around locally for ages)
This modifies message ID generation such that each topic
maintains a monotonic/atomic counter to generate
message IDs, a more scalable and performant approach.
> nsqd: per-topic message IDs

- apps/nsqadmin/main.go
- apps/nsqd/nsqd.go
- apps/nsqlookupd/nsqlookupd.go
- nsqadmin/nsqadmin.go
- nsqadmin/options.go
- nsqd/nsqd.go
- nsqd/options.go
- nsqlookupd/nsqlookupd.go
- nsqlookupd/options.go
instantiate Logger in nsqd.New() instead of nsqd.NewOptions(), only if not already present in opts
More options spam, I understand if it's not desired. But if you don't mind this, I'll do this for nsqlookupd and nsqadmin as well.
(why? it's redundant with the service / container name in my setup. not a big deal)
> *: new --log-prefix flag / option

- nsqd/guid_test.go
Just something very minor:
I was thinking about one more small GUID optimization, just for fun, and I came across these benchmarks. I'm now pretty sure any more optimization of the GUID is pointless, given the current structure / locking. It looks like, when trying to benchmark just GUID generation, on my laptop it's faster than the roughly 4000 IDs per millisecond limit imposed by the 12-bit sequence number. The output from the modified benchmark:
```
BenchmarkGUID-2         	20000000	        68.2 ns/op
--- BENCH: BenchmarkGUID-2
guid_test.go:41: okays=1 errors=0 bads=0
guid_test.go:41: okays=100 errors=0 bads=0
guid_test.go:41: okays=4096 errors=5904 bads=0
guid_test.go:41: okays=275316 errors=724684 bads=0
guid_test.go:41: okays=5328896 errors=14671104 bads=0
PASS
```
I guess the point …
> nsqd: GUID benchmark update

- apps/nsqadmin/main.go
- nsqadmin/http.go
- nsqadmin/http_test.go
- nsqadmin/nsqadmin.go
- nsqadmin/options.go
#769 introduced API endpoints to nsqadmin to update the runtime config value for `nsqlookupd` to give better options for integrating into dynamic environments where restarting the service to pickup new configs is not practical (aka it's running in a container, etc). This also modeled the API after `/config/:opt` endpoints on `nsqd`
Unfortunately `nsqadmin` has a different exposure risk as it's a UI is meant to provide restricted administration changes, unlike `nsqd` which is expected to be on a trusted network. Changing the config for endpoints nsqadmin connects to provides an undesirable vector where you could iteratively change the config and probe internal network endpoints, etc.
Some options to better handle this:
a) nsqadmin could listen on a separate port for the config change API …
> nsqadmin: restrict config change API

- apps/to_nsq/to_nsq.go
This addresses a divide by zero panic that was happening in `to_nsq` (`v1.0.0-compat`) when `--rate` was not set (or was set to 0).
closes https://github.com/nsqio/nsq/issues/866
This is ready for review.
> apps/to_nsq: fix --rate divide by zero bug

- nsqd/protocol_v2.go
- nsqd/protocol_v2_test.go
Fixes #865 
This will return an error to the client when the requested requeue timeout is higher than the `MaxReqTimeout` option, instead of dropping the connection.
> nsqd: clamp requeue timeout to valid range instead of dropping connection	

- apps/nsqd/nsqd.go
- nsqd/options.go
I noticed that --statsd-interval and --msg-timeout are the only two duration flags
that have special functionality to be backwards-compatible with
plain int arguments (meaning seconds or milliseconds).
Is it too late to remove more backwards-compatibility stuff before nsq-1.0?
> nsqd: remove back-compat for flag duration ints

- .travis.yml
- test.sh
Just testing out the ".x" version specifiers for go versions on Travis CI out of curiosity. Feel free to close if not wanted.
> test more go versions on Travis CI

- nsqd/protocol_v2.go
quick hacky fix, instead of "proper" locking
alternative to #886 for fixing #883 
~~not yet tested~~
cc @slayercat
> nsqd: retry sub to ephemeral topic/channel which is Exiting

- README.md
Instead of non-existent segmentio_logo.png it should be segment_logo.png
See: [segment_logo.png](https://github.com/nsqio/nsqio.github.io/blob/master/static/img/segment_logo.png)
> Fix segment.com logo URL in README.md

- nsqd/http.go
- nsqd/stats.go
- nsqd/statsd.go
> nsqd: fix nil pointer when memstats enabled

- nsqd/http.go
- nsqd/http_test.go
According to the docs about `mput`.
> topic - the topic to publish to
> binary - bool ('true' or 'false') to enable binary mode
It indicates that:
* if `binary` param is not specified, text mode is used.
* if `binary` param is specified
* `"true"`, use binary mode
* `"false"`, use text mode
However, according to the implementation, if we specified `binary=false` in the `mput` url, it will be processed as binary mode which is wrong as we currently only check the existence of `binary` url param. :)
/cc @mreiferson @ploxiln @jehiah
> nsqd: fix mpub binary param parsing

- Dockerfile
As 3.6 has been the latest release version for alpine. We should keep in sync.
/cc @mreiferson @ploxiln
> Update alpine base image version

- nsqd/protocol_v2.go
This fixes #926 by properly using the client provided deflate level from identify
> nsqd: fix deflate level handling

- nsqd/channel.go
Upgrade to Go 1.9 and was running benchmarks and observed this panic:
```
$ go test -v -run None -bench ProtocolV2MultiSub*
goos: darwin
goarch: amd64
pkg: github.com/nsqio/nsq/nsqd
BenchmarkProtocolV2MultiSub1-4    	fatal error: concurrent map iteration and map write
goroutine 39 [running]:
runtime.throw(0x14f434f, 0x26)
/usr/local/Cellar/go/1.9/libexec/src/runtime/panic.go:605 +0x95 fp=0xc4203c97e0 sp=0xc4203c97c0 pc=0x102d325
runtime.mapiternext(0xc4203c99a8)
/usr/local/Cellar/go/1.9/libexec/src/runtime/hashmap.go:778 +0x6f1 fp=0xc4203c9878 sp=0xc4203c97e0 pc=0x100ba11
github.com/nsqio/nsq/nsqd.(*Channel).flush(0xc420148000, 0x0, 0x0)
/Users/mreiferson/dev/src/github.com/nsqio/nsq/nsqd/channel.go:224 +0x354 fp=0xc4203c9a18 sp=0xc4203c9878 pc=0x1385f14 …
```
> nsqd: fix flush race

- Godeps
- nsqd/channel.go
- nsqd/topic.go
... so the diskqueue logging integrates with log levels.
The adapter function is needed because the LogLevel types are not defined in the same package, because `go-diskqueue` cannot import `nsq/internal/lg`. If levels were just plain ints this would be cleaner.
See https://github.com/nsqio/go-diskqueue/pull/2 for companion PR. If that is merged I'll update the Godeps in this PR.
cc @mreiferson
> nsqd: diskqueue now takes AppLogFunc instead of Logger

- apps/nsq_to_file/nsq_to_file.go
> nsq_to_file: --topic-pattern causes connection leaks

- apps/nsq_stat/nsq_stat.go
- internal/clusterinfo/data.go
- nsqadmin/http.go
- nsqd/http.go
- nsqd/stats.go
- nsqd/stats_test.go
- nsqd/statsd.go
As nsqd `stats` api supports `format`, `topic` and `channel` url parameters. When displaying info for a specific topic and channel, nsqadmin should query nsqd `stats` api with the specified `topic` and `channel` instead querying all channels under the specified `topic` and laterly filter out the specified channel stats. 
Query stats on demand can reduce the time for nsqadmin api to return and will reduce the possibility  that nsqadmin report timeout when to query a topic with many channels and each channel with many consumer clients.
/cc @mreiferson @ploxiln
> nsqadmin/nsqd: refactor stats querying

- apps/nsq_to_nsq/nsq_to_nsq.go
my proposed changes to #912 
I squashed #912 down to one commit, then added my proposed changes, mostly code-style. See my commit messages. If we agree on these changes, I'll squash most of my changes (all but the last commit) into @jlr52's commit (which will keep his authorship).
The biggest change is to re-inline `commandLineValidation()` and `initConsumerAndHandler()` into `main()` - this is admittedly subjective, but the reasoning is that it reduces the diff against master to about half of what #912 was.
I'll do my own quick manual tests now (but I'm confident :). Take a quick look and let me know what you think @jlr52 @mreiferson
> nsq_to_nsq: multiple topics support

- internal/http_api/api_request.go
More timeouts and limits were added to http.Transport in go-1.7.
Some that were enabled in http.DefaultTransport ended up disabled
in nsq's with-custom-timeouts http.Transport.
IdleConnTimeout in particular is helpful.
see DefaultTransport at https://golang.org/pkg/net/http/#RoundTripper
Not yet field-tested :)
> internal/http_api: update NewDeadlineTransport() with new go http features

- .travis.yml
- Dockerfile
- apps/nsq_tail/nsq_tail.go
- coverage.sh
- dist.sh
I've used NSQ for one of our projects - It is cool system, thanks!
But I had very annoying problem - We have more than 5 queues and for each I should start new container of nsq_tail:
```yaml
version: '3.2'
services:
nsqtail:
image: nsqio/nsq
command: /nsq_tail --topic=mytopic1 --lookupd-http-address=nsqlookupd:4161
nsqtail2:
image: nsqio/nsq
command: /nsq_tail --topic=mytopic2 --lookupd-http-address=nsqlookupd:4161
nsqtail3:
image: nsqio/nsq
command: /nsq_tail --topic=mytopic3 --lookupd-http-address=nsqlookupd:4161
...
```
I know that Docker is "lightweight" system... But not lightweight-enough for running too many containers for simple tasks. So my idea was to make `nsq_tail` listen for multiple topics at once and write all messages from them. Now I can do simply:
```yaml
version: '3.2' …
```
> *: multi-topic nsq_tail; automated docker builds; etc

- apps/nsq_to_file/topic_discoverer.go
This fixes a regresion from #936 where refactoring broke the term handler. The code handling the term signal was only `break`ing out of the `switch` not the `for` loop.
This created the following effect where after a TERM, the process would flush the file and stop, but it wouldn't exit. A subsequent term would crash the process with a double close.
```
[20180102 01:13:55] starting /bitly/service/nsq_chaunceys_log_to_file
2018/01/02 01:13:55 INF    1 [chaunceys_log/nsq_to_file] querying nsqlookupd http://127.0.0.1:4161/lookup?topic=chaunceys_log
2018/01/02 01:13:55 INF    1 [chaunceys_log/nsq_to_file] (127.0.0.1:4150) connecting to nsqd
2018/01/02 01:13:55 INFO: opening /stream_archive/chaunceys_log.dev-000000.2018-01-02_01.log.gz
2018/01/02 01:13:55 syncing 1 records to disk
2018/01/02 …
```
> nsq_to_file: fix term handling 

- internal/clusterinfo/data.go
Nsqadmin fails to format nsqd queries for stats on an ephermal channel. This results in the channel view incorrectly showing no data.
```
[nsqadmin] 2018/01/08 18:49:44.444091 INFO: CI: querying nsqlookupd http://127.0.0.1:4161/lookup?topic=api_requests
[nsqadmin] 2018/01/08 18:49:44.444868 INFO: CI: querying nsqd http://127.0.0.1:4151/stats?format=json&topic=api_requests&channel=tail065817#ephemeral
[nsqadmin] 2018/01/08 18:49:44.445632 INFO: 200 GET /api/topics/api_requests/tail065817%23ephemeral (127.0.0.1:57856) 1.55336ms
```
> nsqadmin: error querying nsqd stats for #ephemeral channel

- nsqd/channel.go
- nsqd/stats.go
- nsqd/stats_test.go
* create inFlightMessages and deferredMessages maps inside mutex.
* acquire appropriate mutexes before doing len() in NewChannelStats()
* add test that checks for passing -race when accessing stats while
serving messages.
Fixes issue #970.
> nsqd: fix lack of synchronization around ChannelStats

- contrib/nsqd.cfg.example
- nsqd/nsqd.go
Passing values greater than 1 makes `quantile` library go nuts and consume lots of memory and CPU after a couple of minutes under ~1000 messages/second. I believe `nsqd` should exit with error instead of pretending that everything's OK in that case.
Also, example config contradicted the nsqd's CLI, which stated that percentile values should be from `(0.0; 1.0]`.
----
Addresses #899.
> nsqd: Validate E2E percentiles & fix the config example

- apps/nsq_tail/nsq_tail.go
This fixes a regression from #957 which added a `fmt.Printf` line which outputs to stdout. `stdout` is used exclusively by `nsq_tail` to output data, and logging should be on `stderr` via the `log` package.
> nsq_tail: mv stdout logging to stderr

- nsqd/lookup.go
This PR will avoid the topic sync accumulation when error in trying to connect to nsqlookupd for register or unregister.
Currently, if nsqd can not do register/unregister a topic/channel, the `lp` address is sent to `syncTopicChan`. Because `syncTopicChan` is a blocked channel, the goroutine for writing `lp` to `syncTopicChan` will be accumulation. After the network to nsqlookupd is ok, the accumulated requests in `syncTopicChan` will be consumed by nsqd and a full topic/channel register will be operated. This will cause a performance downgrade for a busy nsqd instance. 
The proper way to handle identify error is just logging and returning instead of still writing `lp` to `syncTopicChan`.
/cc @mreiferson @jehiah @ploxiln
> nsqd: fix full topic sync accumulation

- nsqd/protocol_v2.go
This PR will make `bytes.Buffer` local variable for each message instead of a global one for each connection. 
Image Once we have a very large message, for example 20MB, after we `SendMessage` with the global `bytes.Buffer`, the underlying array will be expanded to more than 20MB to contain this large message. However, after the large message is sent, the `bytes.Buffer` will not shrink to decrease memory consumption until the connection is closed and `bytes.Buffer` is GCed. And, once more larger messages need to be processed for a connection, the `butes.Buffer` will be continuously enlarged.
We should make `butes.Buffer` a local variable for each message. This will definitely increase the cpu usage as we have more objects which are needed to be GC. But after several iteration GC enhance …
> nsqd: fix memory leak with large message

- internal/util/rand.go
- internal/util/util_test.go
using the Fisher-Yates shuffle algorithm
faster and more consistent runtime when
quantity is near maxval (aka l is near n)
> internal/util: new UniqRands() implementation

- .gitignore
- Gopkg.lock
- Gopkg.toml
- apps/nsqd/nsqd.go
- contrib/nsqd.cfg.example
- internal/statsd/client.go
- internal/writers/boundary_buffered_writer.go
- internal/writers/spread_writer.go
- nsqd/options.go
- nsqd/statsd.go
We've been experiencing some significant UDP packet loss between `nsqd` and our metrics agent on our clusters. These nodes handle 100s of topics/channels.
This set of changes does two things:
1. Buffers the (extremely) granular statsd UDP packets and flushes them at the 508 byte mark.
2. Spreads the packets out over the configured statsd interval rather than bursting each loop.
In combination, this reduces both the number and rate of UDP packets, which should significantly reduce packet loss due to various buffer overflows and whatnot.
Thoughts @ploxiln @jehiah @itwasntandy
> nsqd: buffer and spread UDP statsd writes

- nsqd/lookup.go
- nsqd/lookup_peer.go
- nsqd/nsqd_test.go
Remove syncTopicChan and do the initial REGISTER commands in
the lookupPeer connectCallback(). This should be mostly
equivalent, just with less indirection.
Close() the lookupPeer in all error cases. It will attempt to
re-connect with the next Ping command.
This stuff was brought up in #993 - consider this an un-tested proposal. Please question/comment :)
> nsqd: nsqlookupd connect callback simpler, more robust

- nsqadmin/http_test.go
- nsqadmin/nsqadmin.go
- nsqd/nsqd.go
- nsqlookupd/http_test.go
- nsqlookupd/nsqlookupd.go
not really needed if we create all listeners before starting servers
and run Main() functions to start these synchronously in tests
(I'm not 100% confident though, I could be wrong ...)
> remove locking around listeners for nsqd, nsqlookupd, nsqadmin

- nsqd/nsqd.go
#1031 
I am not sure will this introduce other bugs~
This is what the pr do：
Initialize topic with `pause=1`, so when start `t.messagePump` goroutine，it won't read msg out. 
In the method `GetTopic`，after `NewTopic` return, check `n.isLoading` to see if it is loading from metadata file(restart). If not, unpause it immediately, else, unpause it when all channels are created in `LoadMetadata `. 
`NewTopic` is only called by `GetTopic`， so the change should not affect other code.
------
> nsqd: message loss during topic/channel bootstrap from metadata

- apps/nsqlookupd/nsqlookupd.go
- nsqlookupd/nsqlookupd.go
for package importers to get error info, and to allow importers avoid a call to os.Exit.
fixes #1003
> nsqlookupd: better API when used as a library

- nsqlookupd/registration_db.go
- nsqlookupd/registration_db_test.go
I refactored and added a bit to @andyxning's benchmark from #1036 
Results:
```
benchmark                                  old ns/op     new ns/op     delta
BenchmarkLookupRegistrations8x8-4          1065          1088          +2.16%
BenchmarkLookupRegistrations8x64-4         2264          1165          -48.54%
BenchmarkLookupRegistrations64x64-4        18669         8364          -55.20%
BenchmarkLookupRegistrations64x512-4       134794        10933         -91.89%
BenchmarkLookupRegistrations512x512-4      1698650       150939        -91.11%
BenchmarkLookupRegistrations512x2048-4     5751659       177923        -96.91%
BenchmarkFindProducers8x8-4                244           619           +153.69%
BenchmarkFindProducers8x64-4               243           2259          +829.63% …
```
> nsqlookupd: use map for producers - with benchmarks

- internal/writers/spread_writer.go
- nsqd/nsqd.go
- nsqd/statsd.go
to avoid potential long delay when exiting nsqd
not sure if we can come up with a more elegant fix
cc @mreiferson
> nsqd: make statsd SpreadWriter use exit chan

- nsqd/nsqd.go
- nsqd/topic.go
Enables simplifications. Experimental, not fully tested.
Alternative to #1049. cc @mreiferson
> nsqd: create Topic paused

- nsqadmin/nsqadmin.go
- nsqd/nsqd.go
- nsqd/topic.go
with new Topic.Start()
and make Topic.Pause() and Topic.GetChannel() no longer block
on the notification channels for Topic.messagePump()
and simplify some calls to WaitGroupWrapper.Wrap()
follow-up to #1050 cc @mreiferson 
possibly better, but does change the behavior of Pause() and GetChannel() slightly ...
> nsqd: start Topic messagePump separately from create

- dist.sh
no longer uses local cross-built binaries
(now built in separate docker container)
"-f" flag for "docker tag" is obsolete
also misc checklist/instructions updates
(homebrew update not urgent IMHO, someone else will probably take care of it in a week anyway)
cc @mreiferson @jehiah
> update dist.sh docker build

- apps/nsq_to_file/file_logger.go
- apps/nsq_to_file/nsq_to_file.go
This PR adds a new CLI option `rotate-check-interval` (default 30s) to `nsq_to_file` that controls the frequency at which FileLogger checks whether a file should be rotated.  Fixes #1070.
> nsq_to_file: new flag -rotate-check-interval

- nsqd/client_v2.go
- nsqd/http.go
- nsqd/nsqd.go
- nsqd/protocol_v2.go
- nsqd/stats.go
add /producer_stats endpoint for nsqd. #879
> nsqd: add producer client connections to /stats

- apps/nsq_to_file/file_logger.go
- apps/nsq_to_file/nsq_to_file.go
Renaming this option, as discussed in https://github.com/nsqio/nsq/pull/1071.
> apps/nsq_to_file: rename flag -rotate-check-interval to -sync-interval

- README.md
[Gitee.com](https://gitee.com) used NSQ in production services, We hope to add gitee logo into README.
> README: Add Gitee.com logo

- apps/nsq_to_http/http.go
- apps/nsq_to_http/nsq_to_http.go
- apps/nsq_to_http/nsq_to_http_test.go
Signed-off-by: Alwin Doss <alwindoss84@gmail.com>
> nsq_to_http: add custom header flag

- nsqlookupd/http.go
- nsqlookupd/registration_db.go
Enhance performance for nodes api.
This PR will avoid an additional loop to produce the final result.
The cpu pprof shows that the  map iterator of `ProducerMap2Slice` will consume most of the CPU cycle when requesting `nodes` api.
> go tool pprof 'http://10.8.50.84:4161/debug/pprof/profile'
Fetching profile over HTTP from http://10.8.50.84:4161/debug/pprof/profile
Local symbolization failed for nsqlookupd-0.3.8-ttv2: open /data00/tiger/nsq_deploy/bin/nsqlookupd-0.3.8-ttv2: no such file or directory
Some binary filenames not available. Symbolization may be incomplete.
Try setting PPROF_BINARY_PATH to the search path for local binaries.
Saved profile in /Users/andy/pprof/pprof.nsqlookupd-0.3.8-ttv2.samples.cpu.002.pb.gz
File: nsqlookupd-0.3.8-ttv2
Type: cpu
Time: Nov 8, 2018 at 11:35am …
> lookupd: enhance performance for nodes api

- nsqd/topic.go
As the topic says, topic.messageCount may be less than actually when using topic.PutMessages to write message to backend occurs an error.
> nsqd: fix topic.messageCount on error

- apps/nsq_to_file/file_logger.go
- apps/nsq_to_file/nsq_to_file.go
There are a couple of edge cases we currently need to guard against when shipping the archive files generated by `nsq_to_file` to remote storage (e.g. S3).
1. **Skipping files for the current hour to which nsq_to_file is actively writing incoming messages.**  This requires our sync scripts to know how nsq_to_file will be bucketing files by time, so they can manually exclude the current bucket.
2. **Skipping corrupted gzip files that can arise from the combination of using `nsq_to_file -gzip` and an unclean exit (e.g. `kill -9`).**  We don't currently have a good workaround for this issue, which causes issues in downstream systems and requires manual intervention to remediate.
If `nsq_to_file` used a separate "working dir" for the files to which it is actively writing and only moved files …
> nsq_to_file: support for separate working dir for in-progress files

- internal/auth/authorizations.go
- nsqd/client_v2.go
- nsqd/protocol_v2.go
- nsqd/protocol_v2_test.go
> nsqd: send client TLS cert common_name on authd requests

- apps/nsq_to_file/file_logger.go
In case we're all swayed by @jehiah's arguments in https://github.com/nsqio/nsq/pull/1117#discussion_r245462312 I opened this easy PR.
I'll squash before merge - I left the mechanical revert separate from additional tweaks needed due to the rest of the refactor, for possibly easier review.
cc @mreiferson
> nsq_to_file: revert gzip behavior change

- apps/nsq_to_file/file_logger.go
instead of calling `needsRotation()` because it is theoretically possible that the time-format could
roll-over in the middle of the `updateFile()` rev-incr loop, so `needsRotation()` would always return `true`, and the loop would never terminate.
cc @mreiferson @jehiah 
I thought of this while playing with @mccutchen's `nsq_to_file_jepsen.go` and tweaking it to work with non-gzip mode as well. That doesn't work because all the concurrent `nsq_to_file` instances using the same filename format at the same time can open the same file as each other in append mode (if not using gzip), so only one successfully moves the file and the others fail due to source file missing, and exit with failure. (This seems like "working as designed" to me.)
While figuring that out, I figured that calling …
> nsq_to_file: check for rotate size specifically in rev-incr loop

- apps/nsqd/nsqd.go
- nsqd/client_v2.go
- nsqd/options.go
This PR adds support for customising server output-buffer-timeout default value. 
We have encountered with a single nsqd instance with more than 40k connections. With a default 250ms output buffer timeout we have a high cpu usage. After customising it with 500ms, the CPU
usage drops about 10%.
> nsqd: add support for customise output-buffer-timeout

- nsqd/stats.go
- nsqd/statsd.go
- nsqd/topic.go
This PR adds message size per topic for HTTP protocol. In order to avoid more CPU usage to compute the length for messages, this PR leverage the HTTP header `Content-Length` for message length. As for MPUB, this includes the meta bytes involved in encoding multiple messages.
> nsqd: instrument aggregate message bytes on topics

- internal/http_api/api_response.go
Error messages that get bubbled up are returned from the API wrapped
using a call to fmt.Sprintf(`{"message":"%s"}`, data). Double quotes
appearing inside `data` are unescaped causing incorrectly formatted JSON
(which breaks the UI).
> internal/http_api: fixed error messages quoting

- apps/nsqd/nsqd.go
- nsqd/client_v2.go
- nsqd/options.go
Lower timeouts are more expensive for nsqd, so it seems odd to put
a maximum on the timeout a client can request, but not a minimum.
Also change `--max-output-buffer-timeout` default to 30 seconds,
up from 1 second. Again, it's cheaper/easier for nsqd.
But we may still want to help people avoid unwittingly setting
it close to (or above) the default `--msg-timeout` (60 seconds).
----
I wasn't familiar with `output_buffer_timeout` until #1125 came up. I don't have a real need for these options changes, they just seem to make a bit more sense. But what do you think @mreiferson ?
possibly useful links to refresh memory:
https://github.com/nsqio/nsq/pull/236/commits/043b79acda5fe57056b3cc21b2ef536d5615a2c2
https://nsq.io/clients/tcp_protocol_spec.html#identify
> nsqd: add flag --min-output-buffer-timeout with default 25ms

- apps/nsqd/nsqd.go
- nsqd/channel.go
- nsqd/channel_test.go
- nsqd/nsqd_test.go
- nsqd/options.go
- nsqd/protocol_v2.go
This PR adds `max_channel_client_connection_count` to nsqd to limit the client connection count per channel.
This is mainly used to limit the channel consumer connections per channel.
> nsqd: add max_channel_client_connection_count

- apps/nsq_to_file/file_logger.go
We've been running `nsq_to_file` with "topic discovery" mode on and none of the non go-nsq log messages include enough context to be useful.
> nsq_to_file: include topic/channel for all logging output

- nsqd/tcp.go
Prevent a lot of CLOSE_WAIT。
The probe service detects if nsqd is alive.
Since there is no call to close here, a lot of CLOSE_WAIT will be generated.
> nsqd: close connections that don't send magic

- internal/auth/authorizations.go
In our production environment
1. we have proxies backended with nsqds
2. auth is on
3. proxy uses a connection pool to request on nsqd
when there is high pub concurrency, proxy will create new connection, thus will query authd. The first authd will be overload, and the latency will increase, result in the risk of avalanche. Add a load balance for authd can ease that.
on consumer sides, we also have a large number of consumer instances, Load balance for authd is also benefit.
ready for review
> nsqd: add random load balancing for Authd query

- apps/nsqd/options.go
- nsqd/options.go
This PR adds `queue-scan-worker-pool-max` command line argument.
In our case, the cluster is about 600+ channels and a defer channel with high qps, the phenomenon is that the defer channel message has a large e2e delay beyond the deferred time. The root reason is that for nsqd, there are at most 4 scan worker which is too small for our cluster.
After setting `queue-scan-worker-pool-max` to 64, the defer message delay is more accurate.
> nsqd: add some queue-scan options flags

- nsqd/channel.go
- nsqd/topic.go
Note: generally, we intend to save all the message in the disk-queue when set `-mem-queue-size=0` option, but `make(chan *Message, 0)` just create a unbuffered chan which can also send/receive message as well.
the Go channel spec dictates that nil channel operations (read or write) in a select are skipped, we set memoryMsgChan as not nil noly when mem-queue-size > 0 as shown in [diskqueue.go](https://github.com/nsqio/go-diskqueue/blob/master/diskqueue.go#L636)
> nsqd: set memoryMsgChan as nil when --mem-queue-size=0

- internal/protocol/tcp_server.go
- nsqlookupd/lookup_protocol_v1_test.go
- nsqlookupd/nsqlookupd.go
- nsqlookupd/tcp.go
Fixes the data race seen here: https://github.com/nsqio/nsq/issues/1157 by providing a mechanism for all handler goroutines in `nsqlookupd` to exit before tests finish.
I'm obviously new here so let me know if there are better/simpler ways to accomplish this.
> nsqlookupd: synchronize goroutines to avoid t.Log data races

- Dockerfile
- test.sh
also:
* update alpine version
* revise comments about volumes /data and /etc/ssl/certs
* test.sh works with other posix shells besides bash (e.g. dash in alpine)
inspired by #1196
cc @jehiah
> Dockerfile: WORKDIR /data so nsqd stores stuff in /data by default

- nsqd/nsqd.go
- nsqd/tcp.go
Consumer connections are closed when topics are closed,
but tcp-protocol publish connections are not,
so add tcpServer.CloseAll().
problem introduced by https://github.com/nsqio/nsq/pull/1190
cc @jehiah @mreiferson
> nsqd: fix stall in Exit() due to tcp producer conns

- internal/pqueue/pqueue_test.go
- nsqd/in_flight_pqueue_test.go
> Replace sort.Sort with sort.Ints

- internal/dirlock/dirlock.go
needs to be "not windows AND not illumos"
was OR - always true because windows is not illumos
(and illumos was broken similarly)
fixes #1203 
follow-up to #1195 
cc @mreiferson @i-sevostyanov @sandeepsgangwar @smalhotra-spirent
> build: fix dirlock build tags for windows build

- internal/dirlock/dirlock.go
- nsqd/nsqd.go
https://github.com/nsqio/nsq/issues/1217
> fix the log when data-path is not exist

- Gopkg.lock
- Gopkg.toml
- go.mod
- go.sum
- nsqd/backend_queue.go
- nsqd/dummy_backend_queue.go
- nsqd/protocol_v2.go
- nsqd/topic.go
- nsqd/topic_test.go
ReadChan return receive-only chan for reading, I also open a pr for https://github.com/nsqio/go-diskqueue/pull/7
> diskqueue ReadChan now receive-only chan

- nsqd/client_v2.go
This PR will reduce the update frequency for `ReadyCount` when the new rdy count equals with the old one.
> nsqd: reduce ReadyCount update frequency

- ChangeLog.md
Hello people!
I'm studing about NSQ and noticed at [Docker Page](https://nsq.io/deployment/docker.html) the link to docker image doesn't work. I came to repo and noticed the same at Changelog.
That is redirecting to https://registry.hub.docker.com/u/nsqio/nsq/ and the correct is https://registry.hub.docker.com/r/nsqio/nsq/ with com/**r**/nsqio/ on route.
This my little contribution, thanks for amazing product.
> fix docker hub url in changelog

- Dockerfile
go upstream might fix this soon, but for now it is rather surprising
see https://github.com/golang/go/issues/35305
> Dockerfile: add nsswitch.conf so go resolver uses /etc/hosts first

- bench/bench.py
replaces #1204
fixes #1202
cc @martingrambow @ploxiln
> *: update and fix benchmark script

- ChangeLog.md
- README.md
- apps/nsqd/README.md
- apps/nsqlookupd/README.md
- nsqadmin/README.md
- nsqadmin/package.json
- nsqadmin/static/js/views/header.hbs
- nsqd/README.md
- nsqlookupd/README.md
I noticed various `http://nsq.io/` links; this updates them to https.
> docs: update nsq.io links from http->https

- internal/stringy/slice.go
- internal/stringy/slice_test.go
Hi there, 
I optimized the function body of stringy.Uniq to get rid of the boolean allocation. 
I applied B and A testing to the optimized and previous version. 
Last benchmark result:
goos: linux
goarch: amd64
pkg: github.com/nsqio/nsq/internal/stringy
BenchmarkUniq **(Old version)**
BenchmarkUniq-16     	125957919	        96.8 ns/op	      48 B/op	       2 allocs/op 
BenchmarkUniqB **(New version)**
BenchmarkUniqB-16    	142343587	        91.5 ns/op	      48 B/op	       2 allocs/op
> internal: optimized uniq function

- .github/workflows/test.yml
- test.sh
also add go-1.14 and go-1.15 to test matrix
TODO: try to add back coveralls
> tests: use GitHub Actions for CI

- apps/nsqd/options.go
- nsqd/lookup.go
- nsqd/nsqd.go
- nsqd/options.go
When using nsqd within containerised instances, we would require not only a different broadcast address but also different ports to which consumers must contact in order to reach the nsqd, thus, solving #1073 .
- adds flags to accept `broadcast-tcp-address` and `broadcast-http-address`
- registers nsqd with lookupd using `broadcast-tcp-address` and `broadcast-http-address` instead of the bound ports
> nsqd: seperate broadcast ports for tcp and http

- nsqadmin/context.go
- nsqadmin/http.go
- nsqadmin/notify.go
- nsqadmin/nsqadmin.go
- nsqd/channel.go
- nsqd/channel_test.go
- nsqd/client_v2.go
- nsqd/context.go
- nsqd/http.go
- nsqd/nsqd.go
- nsqd/nsqd_test.go
- nsqd/protocol_v2.go
- nsqd/protocol_v2_test.go
- nsqd/tcp.go
- nsqd/topic.go
- nsqlookupd/context.go
- nsqlookupd/http.go
- nsqlookupd/lookup_protocol_v1.go
- nsqlookupd/lookup_protocol_v1_test.go
- nsqlookupd/nsqlookupd.go
- nsqlookupd/tcp.go
nsqd use of `*Context` and `*context` predates the stdlib `context.Context` and is now confusing; It was used to qualify references to the application struct often used for accessing configuration. This refactors to just remove the wrapper structs which doesn't significantly reduce clarity of code (and improves it in light of stdlib context)
This refactor is needed to import stdlib `context` anywhere in `nsqd/...` without naming conflicts.
> *: remove *Context

- bench/bench_reader/bench_reader.go
- bench/bench_writer/bench_writer.go
- internal/protocol/protocol.go
- nsqd/channel.go
- nsqd/channel_test.go
- nsqd/client_v2.go
- nsqd/http.go
- nsqd/nsqd.go
- nsqd/protocol_v2.go
- nsqd/protocol_v2_test.go
- nsqd/stats.go
- nsqd/stats_test.go
- nsqd/statsd.go
- nsqd/tcp.go
- nsqlookupd/lookup_protocol_v1.go
- nsqlookupd/lookup_protocol_v1_test.go
- nsqlookupd/nsqlookupd.go
- nsqlookupd/tcp.go
Going through the backlog of PRs that have landed, I propose a simpler alternative to #1198, which fixes a bug introduced in #1190.
We're already tracking _all_ client connections, including producers in `nsqd.clients`, so let's just use it to trigger connection close on exit.
Note: we should probably do this consistently across `nsqd` and `nsqlookupd` w/r/t what struct owns tracking and closing client conns, so maybe I should make a similar set of changes to `nsqlookupd`.
cc @ploxiln
> nsqd: close connections on exit (without another map)

- test.sh
```
./test.sh: 6: [: amd64: unexpected operator
./test.sh: 6: [: arm64: unexpected operator
```
See this in every test run, which means we're never running with `-race`
cc @ploxiln
> *: test script failing to run -race

- nsqd/channel.go
- nsqd/nsqd.go
- nsqd/protocol_v2.go
- nsqd/topic.go
Fixes #1251 
I noticed a few things while debugging this...
The reproducible steps from #1251 caused file descriptor exhaustion in `nsqd` on my macOS laptop (default configuration) The stacktrace from `nsqd` confirmed what had previously been reported, a ton of contention on `nsqd.RWMutex`, but I noticed this in particular:
```goroutine 1830 [runnable]:
syscall.syscall(0x10b9ea0, 0xb, 0x33, 0x0, 0x0, 0x0, 0x0)
/usr/local/Cellar/go/1.15.2/libexec/src/runtime/sys_darwin.go:63 +0x2e
syscall.fcntl(0xb, 0x33, 0x0, 0xc001697c38, 0x10d7df7, 0xc00017b620)
/usr/local/Cellar/go/1.15.2/libexec/src/syscall/zsyscall_darwin_amd64.go:338 +0x58
internal/poll.(*FD).Fsync(0xc00017b620, 0x0, 0x0)
/usr/local/Cellar/go/1.15.2/libexec/src/internal/poll/fd_fsync_darwin.go:18 +0xa8
os.(*File).Sync(0xc000318570, …
```
> nsqd: fix ephemeral channel sub live lock

- apps/nsqd/main.go
- nsqd/nsqd.go
This extracts handling from #1305 to handle repeated calls to nsqd.Exit(). This regression was introduced in #1319
```
panic: close of closed channel"
```
Fixes #1326
> nsqd: handle repeated  calls to Exit()

- apps/nsqd/options.go
- nsqd/options.go
- nsqd/statsd.go
When using nsqd with statsd/graphite ephemeral topics and channels can dramatically increase the number of datasets on the graphite side. This creates an option to filter out those from being written to graphite)
I thought this was existing behaviour but discovered this issue due to a new usage pattern that used a dynamic and frequently changing ephemeral channel name. In my case the `#` was being stripped out of key names and so I had missinterpreted missing graphs in nsqadmin for ephemeral channels as no data in graphite, when it was actually a missmatch between the query and resulting dataset key.
To provide a way to filter out ephemeral topics and channels this adds a new `--statsd-exclude-ephemeral` argument which defaults to false (existing behavior).
> nsqd: configurable to skip ephemeral topics/channels in statsd output

- Dockerfile
we can just use latest stable alpine release (currently 3.14)
also switch build image from golang default (debian-based)
to alpine-based, it's smaller and faster to download
> Dockerfile: update base image from alpine:3.10 to latest

- dist.sh
current nsq images don't support arm64 architecture.  that means we can't run them on AWS Graviton's or Apple M1's natively.
use buildx to build a multi-arch with `linux/amd64,linux/arm64` platform support.
the biggest change is we have to go from separate build and push steps into a single build and push step.  this is because the local docker doesn't support building locally multi-arch images.
based on https://www.docker.com/blog/multi-arch-images/ and https://www.docker.com/blog/multi-arch-build-what-about-circleci/
our upstreams, both `golang:latest` and  alpine:3.10`` support these architectures and more.
addresses: https://github.com/nsqio/nsq/issues/1306
> *: build multi-arch docker images linux/amd64,linux/arm64

- apps/nsqd/main.go
- go.mod
- go.sum
This continues to clean up from #1331 and also fixes #1359
> apps/nsqd: initialize nsqd in Init(); move signal handling to go-svc

- dist.sh
This brings in #1355 and #1361 for integration, also adds `{linux,darwin}/arm64` targets for zip/website distribution, fixing #1324 too.
> *: arm64 builds

- nsqadmin/gulpfile.js
- nsqadmin/package-lock.json
- nsqadmin/package.json
This updates the fronted stack for `nsqadmin` to be installable with `npm v7.13.0` on macOS Catalina.
I ran into issues in #1347 trying to recompile the `nsqadmin` js
Note: `go-bindata` was not used in this PR to update js files.
> nsqadmin: update frontend stack

- dist.sh
The expected behavior is for `dist.sh` to produce a set of local images, to be able to separately push (which matches the behavior of what we do for `.tar.gz` files)
> dist: don't push images

- .gitignore
- go.mod
- go.sum
- internal/dirlock/dirlock.go
- internal/dirlock/dirlock_illumos.go
- internal/dirlock/dirlock_windows.go
- internal/stringy/slice_test.go
- nsqadmin/bindata.go
- nsqadmin/static.go
- nsqadmin/static_debug.go
- nsqadmin/static_legacy.go
- nsqd/dqname.go
- nsqd/dqname_windows.go
PR enables run `make` (build and test) with go1.17 by reformatting for go1.17.  `make` and `.test.sh` still work with go1.16.7.
> reformat for go1.17

- .gitignore
- nsqadmin/.gitignore
* consolidate nsqadmin and root .gitignore
* ignore only /build/, do not ignore nsqadmin/static/build/
* do not ignore test, e.g. nsqd/test/ nsqadmin/test/ are committed
* remove obsolete .godeps, vendor, _site, _posts
(build and test ignores were recently added in https://github.com/nsqio/nsq/pull/1368)
> gitignore: consolidate nsqadmin, only ignore root build, etc

- nsqadmin/nsqadmin.go
- test.sh
but ignore "composite literal uses unkeyed fields"
of which there are currently many violations
> test: add "go vet"

- .github/workflows/test.yml
- apps/nsq_to_file/nsq_to_file.go
also switch go-1.16 and go-1.17 containers to debian bullseye base
also update goveralls install method
> CI: add go-1.17 to test matrix, remove go-1.13

- nsqd/http.go
Added support for below parameters in /info api 
max_heartbeat_interval
max_output_buffer_size
max_output_buffer_timeout
max_deflate_level
> nsqd: update /info api to return more metadata

- nsqd/nsqd.go
- nsqd/nsqd_test.go
Metadata marshaling currently is done via a map containing untyped interfaces, which is unfortunate given that the code also contains a `meta` type used during unmarshaling.
This commit elevates the old `meta` type a bit to be used during both operations. The changeste also exposes a GetMetadata method to return the same metadata type without pushing it to disk. This is useful for use cases where NSQD is embedded into another Go program and some introspection is needed.
> nsqd: use metadata struct for both marshal and unmarshal

- nsqd/channel.go
- nsqd/topic.go
In b3b29b7eff41 / https://github.com/nsqio/nsq/pull/1159 unbuffered
memoryMsgChan were replaced with nil chan for both Topic and Channel
(this only happens if mem-queue-size=0). This inadvertently made
deferred publish never work (with mem-queue-size=0), because some
metadata is lost when messages go through the "backend" disk queue,
but previously messages could go immediately through the topic's
unbuffered chan with their metadata intact, to then be added to each
channel's deferred pqueue. This partial revert brings this part back.
Granted, mem-queue-size=0 never worked very well, in many respects.
For this functionality, at low message publish rates, it seems there
was rarely a problem. But at high message publish rates it was always
likely that some messages would hit the topic disk …
> nsqd: allow unbuffered memory chan if ephemeral or deferred

- contrib/nsqadmin.cfg.example
update ACL and TLS usage for nsqadmin
> contrib: update nsqadmin.cfg.example

- apps/nsqd/options.go
before: "minimum SSL/TLS version acceptable ('ssl3.0', 'tls1.0', 'tls1.1', 'tls1.2' or 'tls1.3') (default 769)"
after:  "minimum SSL/TLS version acceptable ('ssl3.0', 'tls1.0', 'tls1.1', 'tls1.2' or 'tls1.3') (default tls1.0)"
> nsqd: nicer tls-min-version help text default

- nsqd/http.go
In some cases where the message volume is large, the memory occupied by the program cannot be returned to the operating system immediately. You can call this method to enforce execution. However, using this method may cause the system to pause for a period of time, so use it with caution.
> nsqd: add memory release function

- apps/nsqd/options.go
- internal/util/unix_socket.go
- internal/util/util_test.go
- nsqadmin/http_test.go
- nsqadmin/nsqadmin_test.go
- nsqd/client_v2.go
- nsqd/http.go
- nsqd/http_test.go
- nsqd/nsqd.go
- nsqd/nsqd_test.go
- nsqd/protocol_v2_unixsocket_test.go
- nsqd/stats_test.go
Hello, this PR provided unix socket supports.
nsqd may started with
```
/build/nsqd --tcp-address /var/run/nsqd.sock --http-address /var/run/nsqd-http.sock --data-path /var/local/nsqd/
```
I've adopted [pynsq](https://github.com/cloudlinux/pynsq/pull/1) and [go-nsq](https://github.com/cloudlinux/go-nsq/pull/1) for connecting to unix sockets as well. I'll create PRs after resolution.
> Ability to bind unix sockets for nsqd

- internal/writers/spread_writer.go
fixes #1435 
Because the only user of this is `nsqd/statsd.go`, we could just return without sleeping in this case, and the statsd loop has its own ticker to wait on. But I figured, we might as well make `SpreadWriter.flush()` always take the desired amount of time, it might be less confusing if this is ever reused, and it's not hard.
(Another interesting idea is to just add a zero-byte buf to the list of bufs if it is empty, but that does result in a zero-byte write syscall, which you can detect with netcat ... it's probably fine, but it's a bit weird.)
> SpreadWriter: fix flush panic with zero writes

- nsqd/channel.go
Should be placed in the critical section for access.
> nsqd: concurrency safety

- bench/requirements.txt
There are 1 security vulnerabilities found in boto 2.38.0
- [MPS-2022-14768](https://www.oscs1024.com/hd/MPS-2022-14768)
Upgrade boto from 2.38.0 to  for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade boto to 

- nsqadmin/.eslintrc
- nsqadmin/package-lock.json
- nsqadmin/package.json
The nsqadmin ESLint configuration leaves the ECMAScript version unspecified which means it defaults to ES5. ES5 was a sensible default many years ago since nsqadmin doesn't transpile its JS nor are their polyfills for missing ECMAScript functionality. 
That said, it's 2023 and modern browsers support vast majority of features from ES2020 and earlier for several years. ES2020 contains the many of the language features that you'd use on a daily basis in modern JS development.
Concrete numbers in terms of world wide adoption can be seen here:
https://caniuse.com/?search=es2020
In addition to adding `es2020` to the environment list, the `space-before-function-paren` rule has been updated with the inclusion of async anonymous arrow functions. 
Without the rule change:
```js
const foo = async() …
```
> nsqadmin: upgrade supported ECMAScript from ES5 to ES2020 in ESLint.

- apps/nsqd/options.go
- internal/auth/authorizations.go
- internal/clusterinfo/data.go
- internal/http_api/api_request.go
- nsqd/client_v2.go
- nsqd/nsqd.go
- nsqd/nsqd_test.go
- nsqd/options.go
- nsqd/protocol_v2_test.go
- nsqlookupd/nsqlookupd_test.go
This adds support for POST based authentication in addition to GET based authentication.
As described in https://github.com/nsqio/nsq/issues/1486, the default behavior of nsqd to to propagate upward any errors from `net/http` clients which leads to Secret's leakage if the authentication server is unavailble.
> nsqd: support POST auth

- nsqadmin/static/js/lib/handlebars_helpers.js
Changed the `$.param()` calls to `$.param(q, true)` to ensure that arrays are serialized using traditional style, resulting in multiple target parameters instead of target[].
From graphite docs [1]
```
The target param can also be repeated to graph multiple related metrics.
&target=company.server1.loadAvg&target=company.server1.memUsage
```
with the current array param our graphite server is responding with
```
{"errors": {"target": "This parameter is required."}}
```
removing the array from the param fixes the graphs.
[1] https://graphite.readthedocs.io/en/latest/render_api.html#target
> nsqadmin: fix graphite 'target' param serialization

- bench/bench_reader/bench_reader.go
- internal/http_api/http_server.go
- internal/protocol/tcp_server.go
cleanup error handling code, use `net.ErrClosed` instead of `strings.Contains`
> chore: cleanup error handling code
